name: cloudwatch
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.8
  dio: ^4.0.6
  geolocator: ^9.0.1
  get_it: ^7.2.0
  connectivity_plus: ^2.3.5
  dart_ipify: ^1.1.1
  shared_preferences: ^2.0.15
  mockito: ^5.2.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
